### ISSUE TITLE
Reorganize Flask-RESTful Structure

### ISSUE THREAD

**Issue by jacobchh** [luscinia-enterprises/aristotle-resources-service#25]
Take into account

- Java structure
- Embedded objects in MongoDB model fields
- Database interaction services
- Redis authentication feature implementation
- Machine learning structure

**Comment by varun-patel** [comment]
Redis token auth will be dealt with in #3

**Comment by jacobchh** [comment]
> 
> 
> Redis token auth will be dealt with in #3

**Comment by jacobchh** [comment]
Oh more so the structure takes into account how we're dealing with Redis tokens to keep it organized, no implementation. @varun-patel

**Comment by varun-patel** [comment]
> Oh more so the structure takes into account how we're dealing with Redis tokens to keep it organized, no implementation. @varun-patel 

Ok, thanks for clearing that up.
